import PDFDocument from "pdfkit";
import type { FinancialSummary, DailyFinancialData } from "$lib/server/models/financial";

/**
 * Generate a PDF financial report
 * @param summary - Financial summary data
 * @param startDate - Start date for the report
 * @param endDate - End date for the report
 * @returns PDF buffer
 */
export async function generateFinancialReportPDF(
  summary: FinancialSummary,
  startDate?: Date,
  endDate?: Date
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      const buffers: Buffer[] = [];

      doc.on("data", buffers.push.bind(buffers));
      doc.on("end", () => {
        const pdfBuffer = Buffer.concat(buffers);
        resolve(pdfBuffer);
      });
      doc.on("error", reject);

      // Header
      doc
        .fontSize(20)
        .font("Helvetica-Bold")
        .text("Tinytech Financial Report", { align: "center" });

      // Date range
      doc.moveDown();
      doc.fontSize(12).font("Helvetica");
      if (startDate && endDate) {
        doc.text(
          `Period: ${startDate.toLocaleDateString()} - ${endDate.toLocaleDateString()}`,
          { align: "center" }
        );
      } else {
        doc.text("All Time Report", { align: "center" });
      }
      doc.text(`Generated: ${new Date().toLocaleString()}`, {
        align: "center",
      });

      doc.moveDown(2);

      // Summary Section
      doc.fontSize(16).font("Helvetica-Bold").text("Financial Summary");
      doc.moveDown(0.5);
      doc.fontSize(11).font("Helvetica");

      const summaryData = [
        ["Total Revenue", `$${summary.totalRevenue.toFixed(2)}`],
        ["Total Cost", `$${summary.totalCost.toFixed(2)}`],
        ["Total Profit", `$${summary.totalProfit.toFixed(2)}`],
        ["Total Orders", summary.totalOrders.toString()],
        ["Total Items Sold", summary.totalItemsSold.toString()],
        ["Average Order Value", `$${summary.averageOrderValue.toFixed(2)}`],
        ["Profit Margin", `${summary.profitMargin.toFixed(2)}%`],
      ];

      summaryData.forEach(([label, value]) => {
        doc.text(`${label}:`, { continued: true, indent: 20 });
        doc.text(value, { align: "right" });
        doc.moveDown(0.3);
      });

      doc.moveDown();

      // Profit/Loss indicator
      doc.fontSize(14).font("Helvetica-Bold");
      if (summary.totalProfit >= 0) {
        doc.fillColor("green").text(`Profit: $${summary.totalProfit.toFixed(2)}`);
      } else {
        doc.fillColor("red").text(`Loss: $${Math.abs(summary.totalProfit).toFixed(2)}`);
      }
      doc.fillColor("black");

      doc.moveDown(2);

      // Daily Breakdown Section
      if (summary.dailyData.length > 0) {
        doc.fontSize(16).font("Helvetica-Bold").text("Daily Breakdown");
        doc.moveDown(0.5);

        // Table header
        doc.fontSize(10).font("Helvetica-Bold");
        let x = doc.x;
        let y = doc.y;

        doc.text("Date", x, y);
        doc.text("Revenue", x + 100, y);
        doc.text("Cost", x + 200, y);
        doc.text("Profit", x + 300, y);
        doc.text("Orders", x + 400, y);

        y += 15;
        doc.moveTo(x, y).lineTo(x + 480, y).stroke();
        y += 10;

        // Table rows
        doc.font("Helvetica");
        summary.dailyData.forEach((day: DailyFinancialData) => {
          if (y > 750) {
            // New page if needed
            doc.addPage();
            y = 50;
          }

          const dateFormatted = new Date(day.date).toLocaleDateString();
          doc.text(dateFormatted, x, y);
          doc.text(`$${day.revenue.toFixed(2)}`, x + 100, y);
          doc.text(`$${day.cost.toFixed(2)}`, x + 200, y);
          
          doc.fillColor(day.profit >= 0 ? "green" : "red");
          doc.text(`$${day.profit.toFixed(2)}`, x + 300, y);
          doc.fillColor("black");
          
          doc.text(day.orderCount.toString(), x + 400, y);
          y += 15;
        });
      }

      // Footer
      doc
        .fontSize(8)
        .font("Helvetica")
        .text(
          "Generated by Tinytech Admin Dashboard",
          50,
          doc.page.height - 50,
          { align: "center", width: doc.page.width - 100 }
        );

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}

